#mysql:
#    image: mysql:5.7
    #volumes:
    #    - ./../docker_mysql:/var/lib/mysql/wp
#    ports:
#        - "3306:3306"
#    environment:
#        - MYSQL_ROOT_PASSWORD=password
viwmed:
    image: php:fpm
    ports:
        - "9000:9000"
    volumes:
        - ./../../viwmed.com:/var/www/viwmed
    #links:
    #    - mysql:mysql
wp_sbp:
    build: fpm
    ports:
        - "9001:9000"
    env_file: ./sbp
    volumes:
        - ./../../sportsbetparlay.com:/var/www/sportsbetparlay
    #links:
    #    - mysql:mysql
wp_mipuntopago:
    build: fpm
    ports:
        - "9002:9000"
    env_file: ./mipuntopago
    volumes:
        - ./../../mipuntopago.com:/var/www/mipuntopago
    #links:
    #    - mysql:mysql