# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_comercializacion', '0001_initial'),
        ('admin_datamart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre (*)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dias',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre (*)')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo (*)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de cuenta',
                'verbose_name_plural': 'Tipos de cuenta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre (*)')),
                ('codename', models.CharField(max_length=100, verbose_name='Código (*)')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción (*)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de movimiento',
                'verbose_name_plural': 'Tipos de movimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comercializadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Introduzca el saldo inicial de la comercializadora', max_digits=15, null=True, verbose_name='Saldo inicial (*)')),
                ('saldo_fecha', models.DateField(blank=True, help_text='Introduzca la fecha del saldo inicial de la comercializadora', null=True, verbose_name='Fecha de saldo inicial (*)')),
                ('resumen_personalizado', models.BooleanField(default=False, help_text='En caso de estar activada esta opcion la comercializadora sera gestionada solo desde resumen personalizado.', verbose_name='Resumen personalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.agencias')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bancas')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bloques')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.distribuidores')),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.operadoras')),
                ('resumen_personalizado_comer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora')),
                ('taquilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.taquillas')),
            ],
            options={
                'verbose_name': 'Comercializadora',
                'verbose_name_plural': 'Comercializadoras',
                'ordering': ['operadora', 'bloque', 'banca', 'distribuidor', 'agencia', 'taquilla'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero de cuenta (*)')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción (*)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.operadoras')),
                ('comercializadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora')),
                ('tipocuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bancas')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
            },
        ),
        migrations.CreateModel(
            name='DiaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('actual', models.BooleanField(default=True, verbose_name='Actual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comercializadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.banco')),
            ],
            options={
                'verbose_name': 'Dia de trabajo',
                'verbose_name_plural': 'Dia de trabajos',
            },
        ),
        migrations.CreateModel(
            name='EstatoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bancas')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.operadoras')),
            ],
            options={
                'verbose_name': 'Estado de cuenta',
                'verbose_name_plural': 'Estados de cuenta',
            },
        ),
        migrations.CreateModel(
            name='ResumenAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('premio', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('comision', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('regalia', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('queda', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('participacion', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('saldo_bruto', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('saldo_comer', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('saldo_oper', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('deposito', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('pago', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('ajuste', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('cargo', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('saldo_anterior', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('saldo_actual', models.DecimalField(decimal_places=16, default=0, max_digits=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comercializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensiontiempo')),
            ],
            options={
                'verbose_name': 'Resumen administrativo',
                'verbose_name_plural': 'Resumenes administrativos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número referencia (*)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto (*)')),
                ('fecha', models.DateField(help_text='Fecha del movimiento', verbose_name='Fecha (*)')),
                ('observacion', models.CharField(max_length=200, verbose_name='Observación (*)')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='movimientos', verbose_name='Comprobante ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comercializadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.banco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.banco')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.tipocuenta')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.tipomovimiento')),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pc', 'Por cobrar'), ('pp', 'Por pagar')], max_length=2)),
                ('min', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comercializadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora')),
            ],
            options={
                'verbose_name': 'Configuracion comercializadora',
                'verbose_name_plural': 'Configuraciones de las comercializadoras',
                'unique_together': {('comercializadora', 'tipo')},
            },
        ),
    ]
