# Generated by Django 6.0.3 on 2026-03-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_cuenta', to='admin_finanzas.banco'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_user', to='admin_finanzas.banco'),
        ),
    ]
