# Generated by Django 6.0.3 on 2026-03-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_comercializacion', '0002_initial'),
        ('admin_finanzas', '0002_alter_movimiento_cuenta_alter_movimiento_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercializadora',
            name='agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.agencias'),
        ),
        migrations.AlterField(
            model_name='comercializadora',
            name='banca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bancas'),
        ),
        migrations.AlterField(
            model_name='comercializadora',
            name='bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bloques'),
        ),
        migrations.AlterField(
            model_name='comercializadora',
            name='distribuidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.distribuidores'),
        ),
        migrations.AlterField(
            model_name='comercializadora',
            name='operadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.operadoras'),
        ),
        migrations.AlterField(
            model_name='comercializadora',
            name='resumen_personalizado_comer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_finanzas.comercializadora'),
        ),
        migrations.AlterField(
            model_name='comercializadora',
            name='taquilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.taquillas'),
        ),
    ]
