# Generated by Django 6.0.3 on 2026-03-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_finanzas', '0003_comercializadora_fks_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diatrabajo',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.dia', verbose_name='Día'),
        ),
    ]
