# Generated by Django 6.0.3 on 2026-03-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=140, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_premio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_ganancia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateTimeField(db_index=True)),
                ('puntaje_calculado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pks_jugadas', models.CharField(db_index=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_tablespace': 'ts_finance',
            },
        ),
        migrations.CreateModel(
            name='TicketsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=16, max_digits=30)),
                ('logro_apostado', models.IntegerField(blank=True, null=True)),
                ('puntaje_calculado', models.IntegerField(blank=True, null=True)),
                ('puntaje_apostado', models.IntegerField(blank=True, null=True)),
                ('modalidad_ref', models.CharField(blank=True, max_length=140, null=True)),
                ('condicion_ref', models.CharField(blank=True, max_length=140, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle de ticket',
                'verbose_name_plural': 'Detalle de tickets',
                'ordering': ['created_at'],
                'db_tablespace': 'ts_finance',
            },
        ),
        migrations.CreateModel(
            name='TicketsDetailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatus de un item de un ticket',
                'verbose_name_plural': 'Estatus de los items de los tickets',
                'ordering': ['startdate'],
                'db_tablespace': 'ts_finance',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatus de un ticket',
                'verbose_name_plural': 'Estatus de los tickets',
                'ordering': ['startdate'],
                'db_tablespace': 'ts_finance',
            },
        ),
        migrations.CreateModel(
            name='TicketsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codename', models.CharField(db_index=True, max_length=160, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de apuesta para un ticket',
                'verbose_name_plural': 'Tipos de apuestas para los tickes',
                'ordering': ['nombre'],
                'db_tablespace': 'ts_finance',
            },
        ),
    ]
