# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_apuestas', '0001_initial'),
        ('admin_comercializacion', '0001_initial'),
        ('admin_juego', '0001_initial'),
        ('admin_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.apuesta'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.usuariostaquilla'),
        ),
        migrations.AddField(
            model_name='ticketsdetail',
            name='jugada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.apuesta'),
        ),
        migrations.AddField(
            model_name='ticketsdetail',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='ticketsdetail',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_apuestas.tickets'),
        ),
        migrations.AddField(
            model_name='ticketsdetailstatus',
            name='detalle_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_apuestas.ticketsdetail'),
        ),
        migrations.AddField(
            model_name='ticketsdetailstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_apuestas.tickets'),
        ),
    ]
