# Generated by Django 6.0.3 on 2026-03-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apuestas', '0002_initial'),
        ('admin_comercializacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_tickets_user', to='admin_comercializacion.usuariostaquilla'),
        ),
    ]
