# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_datamart', '0001_initial'),
        ('admin_finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hecho1_ventascadenasjuegos',
            name='comercializacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='hecho1_ventascadenasjuegos',
            name='juegos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensionjuegos'),
        ),
        migrations.AddField(
            model_name='hecho1_ventascadenasjuegos',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensiontiempo'),
        ),
        migrations.AddField(
            model_name='hecho2_ventascadenas',
            name='comercializacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='hecho2_ventascadenas',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensiontiempo'),
        ),
        migrations.AddField(
            model_name='hecho2_ventascadenaslinea',
            name='comercializacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='hecho2_ventascadenaslinea',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensiontiempo'),
        ),
        migrations.AddField(
            model_name='hecho5_comisionescadena',
            name='comercializacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='hecho5_comisionescadena',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensiontiempo'),
        ),
        migrations.AddField(
            model_name='hecho6_comisionescadenajuego',
            name='comercializacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='hecho6_comisionescadenajuego',
            name='juegos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensionjuegos'),
        ),
        migrations.AddField(
            model_name='hecho6_comisionescadenajuego',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensiontiempo'),
        ),
        migrations.AddField(
            model_name='hecho7_comisionesquedacadena',
            name='comercializacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='hecho7_comisionesquedacadena',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensiontiempo'),
        ),
        migrations.AddField(
            model_name='hecho8_ventasmonitorlinea',
            name='comercializacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='hecho8_ventasmonitorlinea',
            name='juegos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensionjuegos'),
        ),
        migrations.AddField(
            model_name='hecho8_ventasmonitorlinea',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensiontiempo'),
        ),
        migrations.AddField(
            model_name='hecho9_ventassaldoscadena',
            name='comercializacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='hecho9_ventassaldoscadena',
            name='tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_datamart.dimensiontiempo'),
        ),
    ]
