# Generated by Django 6.0.3 on 2026-03-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_datamart', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolidado',
            options={'ordering': ['-dfecha', 'id_sorteo', 'id_taquilla'], 'verbose_name': 'Consolidado Datamart', 'verbose_name_plural': 'Consolidados Datamart'},
        ),
        migrations.RemoveField(
            model_name='consolidado',
            name='mmonto_venta_externa',
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='dfecha',
            field=models.DateField(db_index=True, help_text='Fecha del consolidado', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_agencia',
            field=models.IntegerField(db_index=True, help_text='Identificación de la Agencia', verbose_name='ID Agencia (Centro de Apuesta)'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_banca',
            field=models.IntegerField(db_index=True, help_text='Identificación de la Banca', verbose_name='ID Banca'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_comercializador',
            field=models.IntegerField(db_index=True, help_text='Identificación del comercializador / bloque (Multi Banca)', verbose_name='ID Comercializador (Bloque)'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_distribuidor',
            field=models.IntegerField(db_index=True, help_text='Identificación del Distribuidor', verbose_name='ID Distribuidor'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_lista',
            field=models.IntegerField(db_index=True, help_text='Identificación de la lista', verbose_name='ID Lista'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_operador',
            field=models.IntegerField(db_index=True, help_text='Identificación del Operador', verbose_name='ID Operador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_perfil_pago_premios',
            field=models.IntegerField(blank=True, help_text='Identificación del perfil de pago de premios', null=True, verbose_name='ID Perfil Pago Premios'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_prestador_servicio',
            field=models.IntegerField(db_index=True, help_text='Identificación del Prestador de Servicio', verbose_name='ID Prestador de Servicio'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_sorteo',
            field=models.IntegerField(db_index=True, help_text='Identificación de sorteo', verbose_name='ID Sorteo'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_taquilla',
            field=models.IntegerField(db_index=True, help_text='Identificación de la Taquilla', verbose_name='ID Taquilla'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='id_tipo_lista',
            field=models.IntegerField(help_text='Identificación del tipo de lista', verbose_name='ID Tipo Lista'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_comision_agc',
            field=models.DecimalField(decimal_places=16, help_text='Monto a pagar en comisión a la agencia', max_digits=30, verbose_name='Monto Comisión Agencia'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_comision_ban',
            field=models.DecimalField(decimal_places=16, help_text='Monto a pagar en comisión a la banca', max_digits=30, verbose_name='Monto Comisión Banca'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_comision_com',
            field=models.DecimalField(decimal_places=16, help_text='Monto a pagar en comisión al Comercializador / bloque', max_digits=30, verbose_name='Monto Comisión Comercializador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_comision_dis',
            field=models.DecimalField(decimal_places=16, help_text='Monto a pagar en comisión al distribuidor', max_digits=30, verbose_name='Monto Comisión Distribuidor'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_premios',
            field=models.DecimalField(decimal_places=2, help_text='Monto total de premios', max_digits=13, verbose_name='Monto Premios'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_regalia_ban',
            field=models.DecimalField(decimal_places=16, help_text='Monto a pagar en regalía a la banca', max_digits=30, verbose_name='Monto Regalía Banca'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_regalia_com',
            field=models.DecimalField(decimal_places=16, help_text='Monto a pagar en regalía al Comercializador / bloque', max_digits=30, verbose_name='Monto Regalía Comercializador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_regalia_dis',
            field=models.DecimalField(decimal_places=16, help_text='Monto a pagar en regalía al distribuidor', max_digits=30, verbose_name='Monto Regalía Distribuidor'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_venta',
            field=models.DecimalField(decimal_places=2, help_text='Monto total de venta', max_digits=13, verbose_name='Monto de Venta'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='mmonto_venta_ganador',
            field=models.DecimalField(decimal_places=2, help_text='Monto de Venta al número ganador', max_digits=13, verbose_name='Monto Venta al Nro Ganador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_agc',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Saldo de la Agencia', max_digits=30, null=True, verbose_name='Saldo Agencia'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_ban',
            field=models.DecimalField(decimal_places=16, help_text='Saldo de la Banca', max_digits=30, verbose_name='Saldo Banca'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_bruto_ban',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Saldo Bruto de la Banca', max_digits=30, null=True, verbose_name='Saldo Bruto Banca'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_bruto_com',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Saldo Bruto del comercializador / bloque', max_digits=30, null=True, verbose_name='Saldo Bruto Comercializador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_bruto_dis',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Saldo Bruto del Distribuidor', max_digits=30, null=True, verbose_name='Saldo Bruto Distribuidor'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_cm',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Saldo Comercializador / Bloque', max_digits=30, null=True, verbose_name='Saldo Comercializador/Bloque'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_com',
            field=models.DecimalField(decimal_places=16, help_text='Saldo del Comercializador / bloque', max_digits=30, verbose_name='Saldo Comercializador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_dis',
            field=models.DecimalField(decimal_places=16, help_text='Saldo del Distribuidor', max_digits=30, verbose_name='Saldo Distribuidor'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_oper',
            field=models.DecimalField(decimal_places=16, help_text='Saldo del Operador', max_digits=30, verbose_name='Saldo Operador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_oper_ban',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Saldo Operador de la Banca', max_digits=30, null=True, verbose_name='Saldo Operador-Banca'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_oper_cm',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Saldo Operador del Comercializador / bloque', max_digits=30, null=True, verbose_name='Saldo Operador-Comercializador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='msaldo_oper_dis',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Saldo Operador del Distribuidor', max_digits=30, null=True, verbose_name='Saldo Operador-Distribuidor'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_comision_agc',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de comisión asignado a la agencia', max_digits=5, verbose_name='% Comisión Agencia'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_comision_ban',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de comisión asignado a la banca', max_digits=5, verbose_name='% Comisión Banca'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_comision_com',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de comisión asignado al comercializador / bloque', max_digits=5, verbose_name='% Comisión Comercializador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_comision_dis',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de comisión asignado al distribuidor', max_digits=5, verbose_name='% Comisión Distribuidor'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_participacion_ban',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de participación asignado a la banca', max_digits=5, verbose_name='% Participación Banca'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_participacion_com',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de participación asignado al comercializador / bloque', max_digits=5, verbose_name='% Participación Comercializador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_participacion_dis',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de participación asignado al distribuidor', max_digits=5, verbose_name='% Participación Distribuidor'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_regalia_ban',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de regalía asignado a la banca', max_digits=5, verbose_name='% Regalía Banca'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_regalia_com',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de regalía asignado al comercializador / bloque', max_digits=5, verbose_name='% Regalía Comercializador'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='nporcentaje_regalia_dis',
            field=models.DecimalField(decimal_places=2, help_text='Valor del Porcentaje de regalía asignado al distribuidor', max_digits=5, verbose_name='% Regalía Distribuidor'),
        ),
        migrations.AlterField(
            model_name='consolidado',
            name='tserial_ifa',
            field=models.CharField(help_text='Serial de la Impresora Fiscal', max_length=50, verbose_name='Serial IFA'),
        ),
        migrations.AddIndex(
            model_name='consolidado',
            index=models.Index(fields=['dfecha', 'id_sorteo'], name='idx_consol_fecha_sorteo'),
        ),
        migrations.AddIndex(
            model_name='consolidado',
            index=models.Index(fields=['id_taquilla', 'dfecha'], name='idx_consol_taquilla_fecha'),
        ),
        migrations.AddIndex(
            model_name='consolidado',
            index=models.Index(fields=['id_agencia', 'dfecha'], name='idx_consol_agencia_fecha'),
        ),
    ]
