# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_comercializacion', '0001_initial'),
        ('admin_finanzas', '0001_initial'),
        ('admin_permisologia', '0002_initial'),
        ('admin_profiles', '0001_initial'),
        ('admin_status', '0001_initial'),
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencias',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='bancas',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_profiles.direcciones'),
        ),
        migrations.AddField(
            model_name='bancas',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='bloques',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_profiles.direcciones'),
        ),
        migrations.AddField(
            model_name='bloques',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='bancas',
            name='bloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bloques'),
        ),
        migrations.AddField(
            model_name='cupos',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.agencias'),
        ),
        migrations.AddField(
            model_name='cupos',
            name='banca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bancas'),
        ),
        migrations.AddField(
            model_name='cupos',
            name='bloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bloques'),
        ),
        migrations.AddField(
            model_name='datadefault',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_permisologia.permissions'),
        ),
        migrations.AddField(
            model_name='distribuidores',
            name='banca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bancas'),
        ),
        migrations.AddField(
            model_name='distribuidores',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_profiles.direcciones'),
        ),
        migrations.AddField(
            model_name='distribuidores',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='cupos',
            name='distribuidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.distribuidores'),
        ),
        migrations.AddField(
            model_name='agencias',
            name='distribuidores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.distribuidores'),
        ),
        migrations.AddField(
            model_name='factorriesgo',
            name='comercializadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='operadoras',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_profiles.direcciones'),
        ),
        migrations.AddField(
            model_name='operadoras',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='cupos',
            name='operadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.operadoras'),
        ),
        migrations.AddField(
            model_name='bloques',
            name='operadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.operadoras'),
        ),
        migrations.AddField(
            model_name='porcentajes',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.agencias'),
        ),
        migrations.AddField(
            model_name='porcentajes',
            name='banca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bancas'),
        ),
        migrations.AddField(
            model_name='porcentajes',
            name='bloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.bloques'),
        ),
        migrations.AddField(
            model_name='porcentajes',
            name='distribuidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.distribuidores'),
        ),
        migrations.AddField(
            model_name='porcentajes',
            name='operadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.operadoras'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='comercializacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='taquillas',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.agencias'),
        ),
        migrations.AddField(
            model_name='porcentajes',
            name='taquilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.taquillas'),
        ),
        migrations.AddField(
            model_name='porcentajes',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.tipoporcentajes'),
        ),
        migrations.AddField(
            model_name='typepreferences',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_permisologia.groups'),
        ),
        migrations.AddField(
            model_name='typepreferences',
            name='profile',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los perfiles de usuario que editan la preferencia', to='admin_users.userprofile', verbose_name='Perfiles de configuracion (*)'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='typepreference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.typepreferences'),
        ),
        migrations.AddField(
            model_name='defaultpreferences',
            name='typepreference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.typepreferences'),
        ),
        migrations.AddField(
            model_name='usuariostaquilla',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='usuariostaquilla',
            name='taquilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.taquillas'),
        ),
        migrations.AlterUniqueTogether(
            name='bancas',
            unique_together={('nombre', 'bloque')},
        ),
        migrations.AlterUniqueTogether(
            name='distribuidores',
            unique_together={('nombre', 'banca')},
        ),
        migrations.AlterUniqueTogether(
            name='agencias',
            unique_together={('nombre', 'distribuidores')},
        ),
        migrations.AlterUniqueTogether(
            name='operadoras',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='bloques',
            unique_together={('nombre', 'operadora')},
        ),
        migrations.AlterUniqueTogether(
            name='taquillas',
            unique_together={('taquilla', 'agencia')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariostaquilla',
            unique_together={('user', 'taquilla')},
        ),
    ]
