# Generated by Django 6.0.3 on 2026-04-21 11:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_comercializacion', '0002_initial'),
        ('admin_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercializadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del comercializador', max_length=100, unique=True, verbose_name='Nombre (*)')),
                ('rif', models.CharField(blank=True, help_text='Ingrese el rif del comercializador', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un RIF venezolano valido. Ej: J-12345678-9', regex='^[VEJPG]-?\\d{7,9}-?\\d$')], verbose_name='Rif ')),
                ('telefono', models.CharField(blank=True, help_text='Ingrese el número telefónico del comercializador', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un numero telefonico valido (10 a 12 digitos)', regex='^\\d{10,12}$')], verbose_name='Número Telefónico ')),
                ('fax', models.CharField(blank=True, help_text='Ingrese el fax del comercializador', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un numero telefonico valido (10 a 12 digitos)', regex='^\\d{10,12}$')], verbose_name='Fax ')),
                ('email', models.EmailField(blank=True, help_text='Ingrese el correo electrónico', max_length=254, null=True, verbose_name='Correo electrónico ')),
                ('direccion', models.CharField(blank=True, help_text='Ingrese la dirección del comercializador', max_length=150, null=True, verbose_name='Dirección ')),
                ('contacto', models.CharField(blank=True, help_text='Ingrese una persona de contacto del comercializador', max_length=100, null=True, verbose_name='Persona de contacto ')),
                ('tipo', models.IntegerField(choices=[('', 'Escoja un comercializador'), (1, 'Distribuidor'), (2, 'Subdistribuidor'), (3, 'Agencia')], help_text='Seleccione el tipo de comercializador', verbose_name='Tipo (*)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comer_suc', models.ForeignKey(blank=True, help_text='Seleccione el comercializador del cual depende este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='admin_comercializacion.comercializadores', verbose_name='Comercializador superior ')),
                ('zona', models.ForeignKey(blank=True, help_text='Seleccione la zona geográfica del comercializador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comercializadores_zona', to='admin_profiles.direcciones', verbose_name='Zona ')),
            ],
            options={
                'verbose_name': 'Comercializador',
                'verbose_name_plural': 'Comercializadores',
                'ordering': ['nombre'],
            },
        ),
    ]
