# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_juego', '0002_initial'),
        ('admin_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.grupossorteo')),
            ],
            options={
                'verbose_name': 'Anotacion',
                'verbose_name_plural': 'Anotaciones por grupo',
                'db_tablespace': 'ts_parley',
            },
        ),
        migrations.CreateModel(
            name='AnotacionesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(blank=True, null=True, verbose_name='Puntaje')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_resultados.anotaciones')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.condiciones')),
                ('encuentro_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteodetalle')),
            ],
            options={
                'verbose_name': 'Anotacion',
                'verbose_name_plural': 'Anotaciones por grupo',
                'db_tablespace': 'ts_parley',
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('processed_number', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteo')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sistemajuego')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status')),
            ],
            options={
                'verbose_name': 'Resultado de un ecuentro',
                'verbose_name_plural': 'Resultados por encuentros',
                'db_tablespace': 'ts_parley',
                'unique_together': {('encuentro', 'sistema')},
            },
        ),
        migrations.AddField(
            model_name='anotaciones',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_resultados.resultados'),
        ),
        migrations.CreateModel(
            name='ResultadosRestric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.grupossorteo')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadjuego')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_resultados.resultados')),
            ],
            options={
                'verbose_name': 'Restriccion de resultado',
                'verbose_name_plural': 'Restricciones de resultados',
                'db_tablespace': 'ts_parley',
            },
        ),
    ]
