upstream sbp_panel_balanceado{
    server panel:8000;
}
server {
    listen 8080;

    server_name digital.admin;
    charset utf-8;

    location /static {
       alias /usr/src/sbp/staticfiles;
       expires 365d;
    }

    location /media {
        alias /usr/src/sbp/admin_banklotsports/media;
        expires 365d;
    }

    location / {
        proxy_pass http://sbp_panel_balanceado;
        proxy_redirect off;
        proxy_read_timeout 5m;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}