# Generated by Django 6.0.3 on 2026-03-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorteo', models.CharField(choices=[('triple_a', 'Triple A'), ('triple_b', 'Triple B'), ('animalito', 'Animalito'), ('pegadito', 'Pegadito'), ('terminal', 'Terminal'), ('cuatro', '4 Cifras'), ('otro', 'Otro')], max_length=40, verbose_name='Sorteo')),
                ('horario', models.CharField(choices=[('10:00 AM', '10:00 AM'), ('01:00 PM', '01:00 PM'), ('04:00 PM', '04:00 PM'), ('07:00 PM', '07:00 PM'), ('11:00 PM', '11:00 PM')], max_length=20, verbose_name='Horario')),
                ('abierto', models.BooleanField(default=True, verbose_name='Abierto')),
                ('cupo_venta', models.PositiveIntegerField(default=0, help_text='0 = sin límite de cupo', verbose_name='Cupo de Venta')),
                ('ventas_hoy', models.PositiveIntegerField(default=0, verbose_name='Ventas Hoy')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Control de Sorteo',
                'verbose_name_plural': 'Control de Sorteos',
                'ordering': ['sorteo', 'horario'],
                'unique_together': {('sorteo', 'horario')},
            },
        ),
    ]
