# Generated by Django 6.0.3 on 2026-03-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsorteo',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Apertura'),
        ),
        migrations.AlterField(
            model_name='controlsorteo',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Cierre'),
        ),
        migrations.AlterField(
            model_name='controlsorteo',
            name='sorteo',
            field=models.CharField(choices=[('triple_a', 'Triple A'), ('triple_b', 'Triple B'), ('triple_signo', 'Triple + Signo'), ('el_arrimao', 'El Arrimao'), ('el_pegadito', 'El Pegadito'), ('animalito', 'Animalito'), ('terminal_a', 'Terminal A'), ('terminal_b', 'Terminal B'), ('triple_c', 'Triple C'), ('terminal_c', 'Terminal C'), ('terminal_signo', 'Terminal + Signo')], max_length=40, verbose_name='Sorteo'),
        ),
    ]
