# Generated by Django 6.0.3 on 2026-03-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_controlsorteo_fecha_apertura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSorteoMatriz',
            fields=[
            ],
            options={
                'verbose_name': '📊 Vista Matriz de Sorteos',
                'verbose_name_plural': '📊 Vista Matriz de Sorteos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api_rest.controlsorteo',),
        ),
    ]
