# Generated by Django 6.0.3 on 2026-04-02 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_controlsorteomatriz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('taquillero', models.CharField(max_length=80, verbose_name='Taquillero')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto Bs')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('mobile', 'Pago Móvil'), ('zelle', 'Zelle'), ('cripto', 'Criptomoneda'), ('otro', 'Otro')], default='efectivo', max_length=25, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, max_length=80, verbose_name='Referencia / Comprobante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('periodo_desde', models.DateField(blank=True, null=True, verbose_name='Período Desde')),
                ('periodo_hasta', models.DateField(blank=True, null=True, verbose_name='Período Hasta')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('confirmado_por', models.CharField(blank=True, max_length=80, verbose_name='Confirmado por')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pago de Taquillero',
                'verbose_name_plural': 'Pagos de Taquilleros',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PremioPagado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Sorteo')),
                ('horario', models.CharField(choices=[('10:00 AM', '10:00 AM'), ('01:00 PM', '01:00 PM'), ('04:00 PM', '04:00 PM'), ('07:00 PM', '07:00 PM'), ('11:00 PM', '11:00 PM')], max_length=20, verbose_name='Horario Sorteo')),
                ('modalidad', models.CharField(choices=[('triple_a', 'Triple A'), ('triple_b', 'Triple B'), ('triple_signo', 'Triple + Signo'), ('el_arrimao', 'El Arrimao'), ('el_pegadito', 'El Pegadito'), ('animalito', 'Animalito'), ('terminal_a', 'Terminal A'), ('terminal_b', 'Terminal B')], max_length=30, verbose_name='Modalidad')),
                ('numero_ganador', models.CharField(max_length=10, verbose_name='Número Ganador')),
                ('ticket_ref', models.CharField(blank=True, max_length=40, verbose_name='Ref. Ticket')),
                ('ganador_nombre', models.CharField(max_length=120, verbose_name='Nombre del Ganador')),
                ('ganador_id', models.CharField(blank=True, max_length=30, verbose_name='Cédula / ID Ganador')),
                ('taquillero', models.CharField(blank=True, max_length=80, verbose_name='Taquillero')),
                ('monto_apuesta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Apostado Bs')),
                ('multiplicador', models.DecimalField(decimal_places=2, default=70, max_digits=8, verbose_name='Multiplicador Premio')),
                ('monto_premio', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto Premio Bs')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado / No Válido'), ('en_proceso', 'En Proceso de Verificación')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('pagado_por', models.CharField(blank=True, max_length=80, verbose_name='Pagado por')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Pago')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premio Pagado',
                'verbose_name_plural': 'Premios Pagados',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('horario', models.CharField(choices=[('10:00 AM', '10:00 AM'), ('01:00 PM', '01:00 PM'), ('04:00 PM', '04:00 PM'), ('07:00 PM', '07:00 PM'), ('11:00 PM', '11:00 PM')], max_length=20, verbose_name='Horario')),
                ('modalidad', models.CharField(choices=[('triple_a', 'Triple A'), ('triple_b', 'Triple B'), ('triple_signo', 'Triple + Signo'), ('el_arrimao', 'El Arrimao'), ('el_pegadito', 'El Pegadito'), ('animalito', 'Animalito'), ('terminal_a', 'Terminal A'), ('terminal_b', 'Terminal B')], max_length=30, verbose_name='Modalidad')),
                ('numero', models.CharField(max_length=10, verbose_name='Número Apostado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Bs')),
                ('taquillero', models.CharField(blank=True, max_length=80, verbose_name='Taquillero')),
                ('ticket_ref', models.CharField(blank=True, max_length=40, verbose_name='Ref. Ticket')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ganador', 'Ganador'), ('perdedor', 'Perdedor'), ('anulado', 'Anulado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transacción de Venta',
                'verbose_name_plural': 'Transacciones de Venta',
                'ordering': ['-creado'],
            },
        ),
    ]
