redis:
  restart: always
  image: redis:latest

rabbit:
  restart: always
  image: rabbitmq:3-management
  env_file: ./../../env.unicornn

panel:
  restart: always
  build: django_app
  volumes:
      - ./../../sbp:/usr/src/sbp
  working_dir: /usr/src/sbp
  env_file: ./../../env.unicornn

ws:
  restart: always
  build: django_app
  volumes:
      - ./../../sbp:/usr/src/sbp
      - ./../../WSWebAPI:/usr/src/WSWebAPI
  working_dir: /usr/src/WSWebAPI
  env_file: ./../../env.unicornn

webapp:
  restart: always
  build: web_app
  volumes:
      - ./../../ParlayWebApp:/usr/src/ParlayWebApp
  working_dir: /usr/src/ParlayWebApp
  env_file: ./../../env.unicornn

nginx:
  restart: always
  build: nginx

nodejs:
  restart: always
  build: nodejs_app
  volumes:
      - ./../../RTParlay:/usr/src/RTParlay
  working_dir: /usr/src/RTParlay
  env_file: ./../../env.unicornn