# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_comercializacion', '0002_initial'),
        ('admin_finanzas', '0001_initial'),
        ('admin_juego', '0001_initial'),
        ('admin_status', '0001_initial'),
        ('admin_themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='apuestadetalle',
            name='animalito',
            field=models.ForeignKey(blank=True, help_text='Solo aplica para tipo de jugada ANIMALITO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuestas', to='admin_juego.animalito'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.condiciones'),
        ),
        migrations.AddField(
            model_name='fechas',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='animalfigura',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='admin_juego.grupoanimales'),
        ),
        migrations.AddField(
            model_name='jugadasinformativas',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.condiciones'),
        ),
        migrations.AddIndex(
            model_name='liquidacionsorteo',
            index=models.Index(fields=['id_sorteo', 'id_banca'], name='idx_liq_sorteo_banca'),
        ),
        migrations.AddIndex(
            model_name='liquidacionsorteo',
            index=models.Index(fields=['id_sorteo', 'id_distribuidor'], name='idx_liq_sorteo_dis'),
        ),
        migrations.AddIndex(
            model_name='liquidacionsorteo',
            index=models.Index(fields=['id_sorteo', 'id_agencia'], name='idx_liq_sorteo_agc'),
        ),
        migrations.AlterUniqueTogether(
            name='liquidacionsorteo',
            unique_together={('id_sorteo', 'id_lista', 'id_agencia', 'id_taquilla')},
        ),
        migrations.AddField(
            model_name='modalidadapuesta',
            name='restriction',
            field=models.ManyToManyField(blank=True, help_text='Selecciones las restricciones a necesarias', to='admin_juego.modalidadapuesta', verbose_name='Restricciones '),
        ),
        migrations.AddField(
            model_name='modalidadgrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.grupossorteo'),
        ),
        migrations.AddField(
            model_name='modalidadgrupo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadjuego'),
        ),
        migrations.AddField(
            model_name='condiciones',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadjuego'),
        ),
        migrations.AddField(
            model_name='modalidadjuego_grupos',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.grupossorteo'),
        ),
        migrations.AddField(
            model_name='modalidadjuego_grupos',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadjuego'),
        ),
        migrations.AddField(
            model_name='modalidadapuesta',
            name='grupo',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los grupos a los que pertenece la modalidad', through='admin_juego.ModalidadJuego_Grupos', to='admin_juego.gruposapuesta', verbose_name='Seleccione los grupos (*)'),
        ),
        migrations.AddField(
            model_name='modalidadperiodo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadjuego'),
        ),
        migrations.AddField(
            model_name='modalidadproducto',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadjuego'),
        ),
        migrations.AddField(
            model_name='numerosorteo',
            name='equipos',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los equipos a los que desea asignar el jugador.', to='admin_juego.modalidadjuego', verbose_name='Seleccione los equipos (*)'),
        ),
        migrations.AddField(
            model_name='periodosorteo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='modalidadperiodo',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.periodosorteo'),
        ),
        migrations.AddField(
            model_name='grupossorteo',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.periodosorteo'),
        ),
        migrations.AddField(
            model_name='fechas',
            name='temporadas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.periodosorteo'),
        ),
        migrations.AddField(
            model_name='plantillajugada',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadas', to='admin_juego.plantillaproducto'),
        ),
        migrations.AddField(
            model_name='productoloteria',
            name='grupo_animales',
            field=models.ForeignKey(blank=True, help_text='Solo para tipo ANIMALITOS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='admin_juego.grupoanimales'),
        ),
        migrations.AddField(
            model_name='productoloteria',
            name='loteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='admin_juego.loteria'),
        ),
        migrations.AddField(
            model_name='restriccionessorteo',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.condiciones'),
        ),
        migrations.AddField(
            model_name='restriccionessorteo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.grupossorteo'),
        ),
        migrations.AddField(
            model_name='restriccionessorteo',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadjuego'),
        ),
        migrations.AddField(
            model_name='resultadosorteo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='admin_juego.productoloteria'),
        ),
        migrations.AddField(
            model_name='sistemajuego',
            name='comercializadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='sistemajuego',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='sistemajuego',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_themes.theme'),
        ),
        migrations.AddField(
            model_name='jugadasinformativas',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sistemajuego'),
        ),
        migrations.AddField(
            model_name='fechas',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sistemajuego'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sistemajuego'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.grupossorteo'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.fechas'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status'),
        ),
        migrations.AddField(
            model_name='jugadasinformativas',
            name='detalle_encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteo'),
        ),
        migrations.AddField(
            model_name='jugadasinformativas',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteo'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='detalle_encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteo'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteo'),
        ),
        migrations.AddField(
            model_name='sorteoarrejuntao',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteos', to='admin_juego.productoloteria'),
        ),
        migrations.AddField(
            model_name='sorteodetalle',
            name='encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteo'),
        ),
        migrations.AddField(
            model_name='sorteodetalle',
            name='equipos_temporadas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadperiodo'),
        ),
        migrations.AddField(
            model_name='sorteodetalle',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.numerosorteo'),
        ),
        migrations.AddField(
            model_name='sorteomodalidades',
            name='encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteo'),
        ),
        migrations.AddField(
            model_name='sorteomodalidades',
            name='modalidad_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadjuego_grupos'),
        ),
        migrations.AddField(
            model_name='sorteomodalidades',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteo'),
        ),
        migrations.AddField(
            model_name='sorteomodalidades',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sistemajuego'),
        ),
        migrations.AddField(
            model_name='jugadasinformativas',
            name='encuentros_modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteomodalidades'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='encuentros_modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.sorteomodalidades'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='admin_juego.productoloteria'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Operador de taquilla que emitió el ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='admin_comercializacion.usuariostaquilla'),
        ),
        migrations.AddField(
            model_name='apuestadetalle',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to='admin_juego.ticket'),
        ),
        migrations.AddField(
            model_name='numerosorteo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tiponumerosorteo'),
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto'),
        ),
        migrations.AddField(
            model_name='tiponumerosorteo',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto'),
        ),
        migrations.AddField(
            model_name='restriccionessorteo',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto'),
        ),
        migrations.AddField(
            model_name='periodosorteo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto'),
        ),
        migrations.AddField(
            model_name='modalidadproducto',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto'),
        ),
        migrations.AddField(
            model_name='modalidadjuego_grupos',
            name='deporte_restriccion',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los deportes a quitar de la relacion entre grupos y modalidad, solo se puede restringir  los seleccionados en un principio para el grupo', to='admin_juego.tipoproducto', verbose_name='TipoProducto a restringir '),
        ),
        migrations.AddField(
            model_name='modalidadjuego',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto'),
        ),
        migrations.AddField(
            model_name='tipoproducto_grupos',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto'),
        ),
        migrations.AddField(
            model_name='tipoproducto_grupos',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.grupossorteo'),
        ),
        migrations.AddField(
            model_name='sorteomodalidades',
            name='deporte_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto_grupos'),
        ),
        migrations.AddField(
            model_name='gruposapuesta',
            name='deporte',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los deportes a los que desea asignar el grupo', through='admin_juego.TipoProducto_Grupos', to='admin_juego.tipoproducto', verbose_name='Seleccione los deportes (*)'),
        ),
        migrations.AlterUniqueTogether(
            name='animalfigura',
            unique_together={('grupo', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='modalidadgrupo',
            unique_together={('equipo', 'grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='modalidadperiodo',
            unique_together={('equipo', 'temporada')},
        ),
        migrations.AlterUniqueTogether(
            name='grupossorteo',
            unique_together={('nombre', 'temporada')},
        ),
        migrations.AlterUniqueTogether(
            name='plantillajugada',
            unique_together={('producto', 'tipo_jugada')},
        ),
        migrations.AlterUniqueTogether(
            name='productoloteria',
            unique_together={('loteria', 'nombre_producto')},
        ),
        migrations.AlterUniqueTogether(
            name='fechas',
            unique_together={('jornada', 'temporadas', 'sistema')},
        ),
        migrations.AlterUniqueTogether(
            name='sorteoarrejuntao',
            unique_together={('producto', 'hora_sorteo')},
        ),
        migrations.AlterUniqueTogether(
            name='sorteodetalle',
            unique_together={('encuentro', 'equipos_temporadas')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sorteo_id', 'anulado'], name='idx_ticket_sorteo_estado'),
        ),
        migrations.AddIndex(
            model_name='apuestadetalle',
            index=models.Index(fields=['estatus', 'tipo_jugada'], name='idx_apuesta_estado_tipo'),
        ),
        migrations.AddIndex(
            model_name='apuestadetalle',
            index=models.Index(fields=['ticket', 'estatus'], name='idx_apuesta_ticket_estado'),
        ),
        migrations.AlterUniqueTogether(
            name='numerosorteo',
            unique_together={('nombre', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoproducto',
            unique_together={('nombre', 'deporte')},
        ),
        migrations.AlterUniqueTogether(
            name='tiponumerosorteo',
            unique_together={('nombre', 'deporte')},
        ),
        migrations.AlterUniqueTogether(
            name='periodosorteo',
            unique_together={('nombre', 'torneo')},
        ),
        migrations.AlterUniqueTogether(
            name='modalidadproducto',
            unique_together={('equipo', 'liga')},
        ),
        migrations.AlterUniqueTogether(
            name='modalidadjuego_grupos',
            unique_together={('modalidad', 'grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='modalidadjuego',
            unique_together={('nombre', 'deporte')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoproducto_grupos',
            unique_together={('deporte', 'grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='sorteomodalidades',
            unique_together={('encuentro', 'deporte_grupo', 'modalidad_grupo', 'sistema')},
        ),
    ]
