# Generated by Django 6.0.3 on 2026-03-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_finanzas', '0002_alter_movimiento_cuenta_alter_movimiento_user'),
        ('admin_juego', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='detalle_encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_detalle_sorteo', to='admin_juego.sorteo'),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='favorito',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Favorito'),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_origen', to='admin_juego.sorteo'),
        ),
        migrations.AlterField(
            model_name='jugadasinformativas',
            name='detalle_encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadas_detalle_sorteo', to='admin_juego.sorteo'),
        ),
        migrations.AlterField(
            model_name='jugadasinformativas',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadas_origen', to='admin_juego.sorteo'),
        ),
        migrations.AlterField(
            model_name='modalidadjuego_grupos',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.gruposapuesta'),
        ),
        migrations.AlterField(
            model_name='modalidadjuego_grupos',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadapuesta'),
        ),
        migrations.AlterField(
            model_name='sistemajuego',
            name='comercializadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistemas_juego_principal', to='admin_finanzas.comercializadora'),
        ),
        migrations.AlterField(
            model_name='sistemajuego',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistemas_juego_company', to='admin_finanzas.comercializadora'),
        ),
        migrations.AlterField(
            model_name='sorteomodalidades',
            name='encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades_sorteo', to='admin_juego.sorteo'),
        ),
        migrations.AlterField(
            model_name='sorteomodalidades',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades_origen', to='admin_juego.sorteo'),
        ),
        migrations.AlterField(
            model_name='tipoproducto_grupos',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.gruposapuesta'),
        ),
    ]
