# Generated by Django 6.0.3 on 2026-03-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_comercializacion', '0002_initial'),
        ('admin_juego', '0003_alter_apuesta_detalle_encuentro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_tickets_diarios', models.PositiveIntegerField(default=0, help_text='0 = sin límite', verbose_name='Máximo de tickets diarios')),
                ('monto_maximo_diario', models.DecimalField(decimal_places=2, default=0, help_text='0.00 = sin límite de monto', max_digits=12, verbose_name='Monto máximo diario')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='admin_comercializacion.agencias', verbose_name='Centro de Apuesta')),
            ],
            options={
                'verbose_name': 'Límite del Centro',
                'verbose_name_plural': 'Límites del Centro',
                'ordering': ['agencia'],
            },
        ),
    ]
