# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la empresa (*)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre del tema (*)')),
                ('codename', models.CharField(max_length=140, verbose_name='Codename del tema (*)')),
                ('description', models.CharField(max_length=140, verbose_name='Descripción del tema (*)')),
                ('screenshoot', models.ImageField(blank=True, null=True, upload_to='themes')),
                ('template_dir', models.CharField(max_length=140, verbose_name='Dirección de template')),
                ('static_url', models.CharField(max_length=140, verbose_name='URL de los archivos estáticos')),
                ('media_url', models.CharField(max_length=140, verbose_name='URL de la carpeta de media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['name'],
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=140, verbose_name='Color (*)')),
                ('color_type', models.IntegerField(choices=[(0, 'Primary'), (1, 'Secondary'), (2, 'Default')], verbose_name='Tipo de color (*)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_themes.theme')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'db_tablespace': 'ts_comer',
                'unique_together': {('theme', 'color'), ('theme', 'color_type')},
            },
        ),
    ]
