# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Nombre del grupo (*)')),
                ('codename', models.CharField(editable=False, max_length=160, unique=True, verbose_name='Codename (*)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='PermissionsSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso Venta',
                'verbose_name_plural': 'Permisos ventas',
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='PermissionsSalesRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrictions', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Restricciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso Venta (Restricciones)',
                'verbose_name_plural': 'Permisos ventas (Restricciones)',
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Titulo ')),
                ('codename', models.CharField(db_index=True, max_length=160, verbose_name='Codigo ')),
                ('url', models.CharField(blank=True, db_index=True, max_length=160, null=True, verbose_name='Url ')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono ')),
                ('content_type', models.IntegerField(blank=True, choices=[(1, 'Titulo princial.'), (2, 'Subtitulo.'), (3, 'Enlace.')], null=True, verbose_name='Nivel ')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden ')),
                ('is_view', models.BooleanField(default=False, verbose_name='Visible ')),
                ('is_public', models.BooleanField(default=False, verbose_name='PÃºblico ')),
                ('is_global', models.BooleanField(default=False, help_text='Enlace privado, pero global', verbose_name='Global ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_suc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_permisologia.menu')),
            ],
            options={
                'verbose_name': 'Menu (url)',
                'verbose_name_plural': 'Menus (enlaces)',
                'ordering': ['orden'],
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Nombre ')),
                ('codename', models.CharField(editable=False, max_length=160, unique=True, verbose_name='Codigo ')),
                ('content_type', models.CharField(choices=[('admin_lib', 'Admin lib'), ('admin_historic', 'Admin historic'), ('admin_juego', 'Admin juego'), ('admin_apuestas', 'Admin apuestas'), ('admin_comercializacion', 'Admin comercializacion'), ('admin_datamart', 'Admin datamart'), ('admin_finanzas', 'Admin finanzas'), ('admin_logros', 'Admin logros'), ('admin_mail', 'Admin mail'), ('admin_permisologia', 'Admin permisologia'), ('admin_principal', 'Admin principal'), ('admin_profiles', 'Admin profiles'), ('admin_reportes', 'Admin reportes'), ('admin_resultados', 'Admin resultados'), ('admin_soporte', 'Admin soporte'), ('admin_status', 'Admin status'), ('admin_themes', 'Admin themes'), ('admin_users', 'Admin users')], max_length=50, verbose_name='App ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ManyToManyField(to='admin_permisologia.menu', verbose_name='Vistas asociadas ')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['content_type', 'name'],
                'db_tablespace': 'ts_comer',
            },
        ),
    ]
