# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_finanzas', '0001_initial'),
        ('admin_juego', '0001_initial'),
        ('admin_permisologia', '0001_initial'),
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='profiles',
            field=models.ManyToManyField(to='admin_users.userprofile', verbose_name='Perfiles asociados '),
        ),
        migrations.AddField(
            model_name='groups',
            name='permissions',
            field=models.ManyToManyField(to='admin_permisologia.permissions', verbose_name='Permisos asociados (*)'),
        ),
        migrations.AddField(
            model_name='permissionssales',
            name='comercializadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='permissionssales',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto'),
        ),
        migrations.AddField(
            model_name='permissionssales',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.grupossorteo'),
        ),
        migrations.AddField(
            model_name='permissionssales',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.modalidadjuego'),
        ),
        migrations.AddField(
            model_name='permissionssalesrestrictions',
            name='comercializadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora'),
        ),
        migrations.AddField(
            model_name='permissionssalesrestrictions',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_juego.tipoproducto'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('codename', 'url')},
        ),
    ]
