upstream sbp_ws_balanceado{
    server unix:/usr/src/WSWebAPI/WSWebAPI_sbp_ws_1.sock;
    server unix:/usr/src/WSWebAPI/WSWebAPI_sbp_ws_2.sock;
}
server {
    listen 8081;
    listen 8082 ssl;

    server_name 179.43.114.158;
    charset utf-8;

    try_files $uri @ws;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location /static {
        alias /usr/src/WSWebAPI/staticfiles;
        expires 365d;
    }

    location /media {
        alias /usr/src/WSWebAPI/ws_sportparley/media;
        expires 365d;
    }

    location / {
        proxy_pass http://sbp_ws_balanceado;
        proxy_redirect off;
        proxy_read_timeout 5m;
        proxy_set_header Host $host:8081;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}