upstream sbp_webapp_balanceado{
    server unix:/usr/src/ParlayWebApp/ParlayWebApp_sbp_webapp_1.sock;
}
server {
    listen 8083;
    server_name 179.43.114.158;
    charset utf-8;

    try_files $uri @webapp;

    location /static {
       alias /usr/src/ParlayWebApp/staticfiles;
       expires 365d;
    }

    location /media {
        alias /usr/src/ParlayWebApp/parlaywebapp/media;
        expires 365d;
    }

    location / {
        proxy_pass http://sbp_webapp_balanceado;
        proxy_redirect off;
        proxy_read_timeout 5m;
        proxy_set_header Host $host:8083;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}