redis:
  restart: always
  image: redis:latest

rabbit:
  restart: always
  image: rabbitmq:3-management
  env_file: ./../../env

panel:
  restart: always
  build: django_app
  volumes:
      - ./../../admin_banklotsports:/usr/src/admin_banklotsports
  working_dir: /usr/src/admin_banklotsports
  env_file: ./../../env

ws:
  restart: always
  build: django_app
  volumes:
      - ./../../admin_banklotsports:/usr/src/admin_banklotsports
      - ./../../ws_sportparley:/usr/src/ws_sportparley
  working_dir: /usr/src/ws_sportparley
  env_file: ./../../env