# Generated by Django 6.0.3 on 2026-03-28 15:29

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HechoConnectionsComer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora_id', models.IntegerField()),
                ('bloque_id', models.IntegerField()),
                ('banca_id', models.IntegerField()),
                ('distribuidor_id', models.IntegerField()),
                ('agencia_id', models.IntegerField()),
                ('taquilla_id', models.IntegerField(db_index=True)),
                ('connection_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hecho de conexion',
                'verbose_name_plural': 'Hecho de conexiones',
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('cookie', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session de usuario',
                'verbose_name_plural': 'Sessiones por usuario',
                'ordering': ['-enddate'],
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='SessionsDetail',
            fields=[
                ('id', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('ref_related', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle de una session',
                'verbose_name_plural': 'Detalle de las sessiones por usuario',
                'ordering': ['-created_at'],
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='TaquillaSessions',
            fields=[
                ('id', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False)),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session por taquilla',
                'verbose_name_plural': 'Sessiones por taquillas',
                'ordering': ['-enddate'],
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='TaquillaSessionsDetail',
            fields=[
                ('id', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False)),
                ('detail', jsonfield.fields.JSONField(blank=True, null=True)),
                ('enrro', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle de la session por taquilla',
                'verbose_name_plural': 'Detalle de las sessiones por taquillas',
                'ordering': ['-created_at'],
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='UsersProcesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('codename', models.CharField(max_length=140, unique=True)),
                ('content_type', models.CharField(blank=True, choices=[('admin_lib', 'Admin lib'), ('admin_historic', 'Admin historic'), ('admin_juego', 'Admin juego'), ('admin_apuestas', 'Admin apuestas'), ('admin_comercializacion', 'Admin comercializacion'), ('admin_datamart', 'Admin datamart'), ('admin_finanzas', 'Admin finanzas'), ('admin_logros', 'Admin logros'), ('admin_mail', 'Admin mail'), ('admin_permisologia', 'Admin permisologia'), ('admin_principal', 'Admin principal'), ('admin_profiles', 'Admin profiles'), ('admin_reportes', 'Admin reportes'), ('admin_resultados', 'Admin resultados'), ('admin_soporte', 'Admin soporte'), ('admin_status', 'Admin status'), ('admin_themes', 'Admin themes'), ('admin_users', 'Admin users')], max_length=50, null=True, verbose_name='App')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de proceso',
                'verbose_name_plural': 'Tipos de procesos',
                'ordering': ['content_type'],
                'db_tablespace': 'ts_comer',
            },
        ),
    ]
