# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_comercializacion', '0001_initial'),
        ('admin_historic', '0001_initial'),
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_users.users'),
        ),
        migrations.AddField(
            model_name='sessionsdetail',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_historic.sessions'),
        ),
        migrations.AddField(
            model_name='taquillasessions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.usuariostaquilla'),
        ),
        migrations.AddField(
            model_name='taquillasessionsdetail',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_historic.taquillasessions'),
        ),
        migrations.AddField(
            model_name='usersprocesses',
            name='process_suc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_historic.usersprocesses'),
        ),
        migrations.AddField(
            model_name='taquillasessionsdetail',
            name='userprocess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_historic.usersprocesses'),
        ),
        migrations.AddField(
            model_name='sessionsdetail',
            name='userprocess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_historic.usersprocesses'),
        ),
    ]
