upstream sbp_panel_balanceado{
    server panel:8000;
}
server {
    listen 80;
    listen 443 ssl;

    server_name admin.unicornn.com;
    charset utf-8;

    ssl_certificate /etc/nginx/ssl/all.crt;
    ssl_certificate_key /etc/nginx/ssl/all.key;

    location /static {
       alias /usr/src/sbp/staticfiles;
       expires 365d;
    }

    location /media {
        alias /usr/src/sbp/admin_banklotsports/media;
        expires 365d;
    }

    location / {
        proxy_pass http://sbp_panel_balanceado;
        proxy_redirect off;
        proxy_read_timeout 5m;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    if ($scheme = http) {
        return 301 https://$server_name$request_uri;
    }
}