#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $PANEL_DB_HISTORIC_NAME;
    CREATE DATABASE $PANEL_DB_DATAMART_NAME;
    CREATE DATABASE $WS_DB_NAME;
EOSQL
