redis:
  extends:
    file: docker-compose-common.yml
    service: redis

rabbit:
  extends:
    file: docker-compose-common.yml
    service: rabbit

postgres:
  extends:
    file: docker-compose-common.yml
    service: postgres

crontab:
  extends:
    file: docker-compose-common.yml
    service: panel
  command: python manage.py celery worker --hostname=crontab -B -E -Q default
  links:
    - redis:redis
    - rabbit:rabbit

worker:
  extends:
    file: docker-compose-common.yml
    service: panel
  command: /etc/app/conf/worker.bash
  links:
    - redis:redis
    - rabbit:rabbit
    - postgres

flower:
  extends:
    file: docker-compose-common.yml
    service: panel
  command: python manage.py celery flower --port=5555 --basic_auth=dig:dig123 --persistent=True
  links:
    - redis:redis
    - rabbit:rabbit

panel:
  extends:
    file: docker-compose-common.yml
    service: panel
  command: /etc/app/conf/panel.bash
  links:
    - redis:redis
    - rabbit:rabbit
    - postgres

ws:
  extends:
    file: docker-compose-common.yml
    service: ws
  command: /etc/app/conf/ws.bash
  links:
    - redis:redis
    - rabbit:rabbit
    - postgres

nginx:
  extends:
    file: docker-compose-common.yml
    service: nginx
  volumes:
    - ./../../../Triple 7/:/usr/src/
  ports:
    - "8080:8080"
    - "8081:8081"
    - "8082:8082"
    - "8083:8083"
    - "8088:8088"
  links:
    - panel:panel
    - ws:ws
    - flower:flower
    - rabbit:rabbit
