# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_datamart', '0028_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensionarcocomercializacion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dimensionarcocomercializacion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dimensioncomercializacion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dimensioncomercializacion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dimensionjuegos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dimensionjuegos',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dimensionjuegosnew',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dimensionjuegosnew',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dimensiontiempo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dimensiontiempo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hecho1_ventascadenasjuegos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hecho1_ventascadenasjuegos',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hecho2_ventascadenas',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hecho2_ventascadenas',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hecho2_ventascadenaslinea',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hecho2_ventascadenaslinea',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hecho5_comisionescadena',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hecho5_comisionescadena',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hecho6_comisionescadenajuego',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hecho6_comisionescadenajuego',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hecho7_comisionesquedacadena',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hecho7_comisionesquedacadena',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hecho8_ventasmonitorlinea',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hecho8_ventasmonitorlinea',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hecho9_ventassaldoscadena',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hecho9_ventassaldoscadena',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='dimensioncomercializacion',
            name='operadora_id',
            field=models.IntegerField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dimensiontiempo',
            name='fecha',
            field=models.DateField(db_index=True),
            preserve_default=True,
        ),
    ]
