# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_comercializacion', '0001_initial'),
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('codename', models.CharField(db_index=True, max_length=160, unique=True)),
                ('content_type', models.IntegerField(choices=[(0, 'Status de actualizacion'), (1, 'Status de usuarios'), (2, 'Status de encuentros'), (3, 'Status de taquillas'), (4, 'Status de jugadas'), (5, 'Status de encuentro resultado'), (6, 'Status de venta de tickets'), (7, 'Status de ??????'), (8, 'Status de tickets')], db_index=True)),
                ('order', models.IntegerField(default=0, help_text='Ingrese la numeraciÃ³n de orden', verbose_name='Orden (*)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
                'ordering': ['content_type'],
            },
        ),
        migrations.CreateModel(
            name='StatusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_users.users')),
            ],
            options={
                'verbose_name': 'Detalle de estatus',
                'verbose_name_plural': 'Detalle de estatus de los usuario',
            },
        ),
        migrations.CreateModel(
            name='TaquillaStatusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_status.status')),
                ('usuariotaquilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_comercializacion.usuariostaquilla')),
            ],
            options={
                'verbose_name': 'Detalle de estatus',
                'verbose_name_plural': 'Detalle de estatus de las taquillas',
            },
        ),
    ]
