# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_finanzas', '0001_initial'),
        ('admin_permisologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('codename', models.CharField(db_index=True, max_length=160, unique=True)),
                ('content_type', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de usuario',
                'verbose_name_plural': 'Tipos de usuarios',
                'ordering': ['content_type'],
                'db_tablespace': 'ts_comer',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user', models.CharField(db_index=True, help_text='Ingrese el nombre de usuario', max_length=100, unique=True, verbose_name='Nombre de usuario (*)')),
                ('etiqueta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Etiqueta ')),
                ('email', models.EmailField(blank=True, help_text='Ingrese el correo electronico', max_length=254, null=True, unique=True, verbose_name='Correo electronico ')),
                ('token', models.CharField(editable=False, max_length=200, null=True)),
                ('token_time', models.DateTimeField(editable=False, null=True)),
                ('superuser', models.BooleanField(default=False, verbose_name='Superusuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comercializadora', models.ManyToManyField(to='admin_finanzas.comercializadora', verbose_name='Comercializadora')),
                ('comercializadora_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora')),
                ('groups', models.ManyToManyField(blank=True, help_text='Seleccione los grupos disponibles', related_name='user_set', related_query_name='user', to='admin_permisologia.groups', verbose_name='Grupos de usuario')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_permisologia.permissions')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Seleccione los permisos para el usuario.', related_name='user_set', related_query_name='user', to='admin_permisologia.permissions', verbose_name='Permisos de usuario')),
                ('user_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_referidos', to='admin_users.users')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['user'],
                'db_tablespace': 'ts_comer',
            },
        ),
    ]
