# Generated by Django 6.0.3 on 2026-03-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_finanzas', '0002_alter_movimiento_cuenta_alter_movimiento_user'),
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='comercializadora_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_sesion', to='admin_finanzas.comercializadora'),
        ),
    ]
