# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import admin_comercializacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0009_auto_20141212_0936'),
        ('admin_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaDataDefault',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('montomin', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montomax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montomax_ganancia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad_apuesta_max', models.IntegerField()),
                ('cantidad_apuesta_min', models.IntegerField()),
                ('tiempoexpiracion', models.IntegerField()),
                ('everyone', models.BooleanField(default=False)),
                ('parley_machos_max', models.IntegerField()),
                ('parley_machos_min', models.IntegerField()),
                ('parley_hembras_max', models.IntegerField()),
                ('parley_hembras_min', models.IntegerField()),
                ('parley_clonados_maxima_ganancia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 236501), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 236561), auto_now=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Agencias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(verbose_name='Nombre de la agencia (*)', null=True, unique=True, max_length=100, blank=True, help_text='Ingrese nombre de la agencia')),
                ('rif', models.CharField(verbose_name='Rif ', help_text='Ingrese el rif de la agencia', null=True, max_length=15, blank=True)),
                ('telefono', models.CharField(verbose_name='Número Telefonico ', help_text='Ingrese el telefono de la agencia', null=True, max_length=12, blank=True)),
                ('email', models.EmailField(verbose_name='Correo electronico ', help_text='Ingrese el correo electronico', null=True, max_length=254, blank=True)),
                ('num_taquillas', models.IntegerField(verbose_name='Número de taquillas (*)', help_text='Seleccione el numero de taquillas a crear automáticamente para la agencia')),
                ('montomin', models.DecimalField(verbose_name='Monto mínimo ', decimal_places=2, help_text='Seleccione el monto mínimo', max_digits=15)),
                ('montomax', models.DecimalField(verbose_name='Monto máximo ', decimal_places=2, help_text='Seleccione el monto máximo', max_digits=15)),
                ('montomax_ganancia', models.DecimalField(verbose_name='Monto máximo de ganancia ', decimal_places=2, help_text='Seleccione el monto máximo de ganancia', max_digits=15)),
                ('cantidad_apuesta_max', models.IntegerField(verbose_name='Cantidad máxima de combinaciones ', help_text='Seleccione la cantidad máxima de combinaciones')),
                ('cantidad_apuesta_min', models.IntegerField(verbose_name='Cantidad minima de combinaciones ', help_text='Seleccione la cantidad minima de combinaciones')),
                ('tiempoexpiracion', models.IntegerField(verbose_name='Días de expiración del los tickets ', help_text='Seleccione la cantidad de días de expiración para los tickets')),
                ('parley_machos_max', models.IntegerField(verbose_name='Parley: Máximo de apuestas a un macho por ticket', help_text='Parley: Seleccione el numero máximo de apuesta a un macho en un ticket')),
                ('parley_machos_min', models.IntegerField(verbose_name='Parley: Mínimo de apuestas a un macho por ticket', help_text='Parley: Seleccione el numero mínimo de apuesta a un macho en un ticket')),
                ('parley_hembras_max', models.IntegerField(verbose_name='Parley: Máximo de apuestas a una hembra por ticket', help_text='Parley: Seleccione el numero máximo de apuesta a una en un ticket')),
                ('parley_hembras_min', models.IntegerField(verbose_name='Parley: Mínimo de apuestas a un hembra por ticket', help_text='Parley: Seleccione el numero mínimo de apuesta a una hembra en un ticket')),
                ('parley_clonados_maxima_ganancia', models.DecimalField(verbose_name='Parley: Monto máximo de ganancia para combinaciones repetidas en tickets', decimal_places=2, help_text='Parley: Seleccione el monto máximo para la ganancia de apuestas con combinaciones repetidas en los tickets', max_digits=15)),
                ('status_id', models.IntegerField(verbose_name='Estatus de la operadora (*)', help_text='Seleccione el status deseado')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 250178), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 250236), auto_now=True)),
                ('direccion_id', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases = (models.Model,),
        ),
        migrations.CreateModel(
            name='Bancas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(verbose_name='Nombre de la banca (*)', null=True, unique=True, max_length=100, blank=True, help_text='Ingrese nombre de la banca')),
                ('rif', models.CharField(verbose_name='Rif ', help_text='Ingrese el rif de la banca', null=True, max_length=15, blank=True)),
                ('telefono', models.CharField(verbose_name='Número Telefonico ', help_text='Ingrese el telefono de la banca', null=True, max_length=12, blank=True)),
                ('email', models.EmailField(verbose_name='Correo electronico ', help_text='Ingrese el correo electronico', null=True, max_length=254, blank=True)),
                ('status_id', models.IntegerField(verbose_name='Estatus de la operadora (*)', help_text='Seleccione el status deseado')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 245912), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 245970), auto_now=True)),
                ('direccion_id', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(admin_comercializacion.models.BaseGenericProcess, models.Model),
        ),
        migrations.CreateModel(
            name='Bloques',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(verbose_name='Nombre del bloque (*)', unique=True, max_length=100, help_text='Ingrese el nombre del bloque')),
                ('rif', models.CharField(verbose_name='Rif ', help_text='Ingrese el rif del bloque', null=True, max_length=15, blank=True)),
                ('telefono', models.CharField(verbose_name='Número Telefonico ', help_text='Ingrese el telefono del bloque', null=True, max_length=12, blank=True)),
                ('email', models.EmailField(verbose_name='Correo electronico ', help_text='Ingrese el correo electronico', null=True, max_length=254, blank=True)),
                ('tipo', models.BooleanField(verbose_name='¿Para venta web? ', default=False, help_text='En caso de ser un bloque para venta en la web, seleccione este campo')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 244010), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 244072), auto_now=True)),
                ('status_id', models.IntegerField(verbose_name='Estatus de la operadora (*)', help_text='Seleccione el status deseado')),
                ('direccion_id', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(admin_comercializacion.models.BaseGenericProcess, models.Model),
        ),
        migrations.CreateModel(
            name='Cupos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(null=True, blank=True)),
                ('monto_diario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 255437), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 255494), auto_now=True)),
                ('agencia', models.ForeignKey(null=True, to='admin_comercializacion.Agencias', blank=True)),
                ('banca', models.ForeignKey(null=True, to='admin_comercializacion.Bancas', blank=True)),
                ('bloque', models.ForeignKey(null=True, to='admin_comercializacion.Bloques', blank=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DataDefault',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cupo', models.DecimalField(decimal_places=5, max_digits=15)),
                ('porcentaje_comision', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('porcentaje_regalia', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('porcentaje_participacion', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('porcentaje_maximo', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('dias', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 240473), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 240533), auto_now=True)),
                ('user_type', models.ForeignKey(to='admin_users.UserProfile')),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Distribuidores',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(verbose_name='Nombre del distribuidor (*)', null=True, unique=True, max_length=100, blank=True, help_text='Ingrese nombre del distribuidor')),
                ('rif', models.CharField(verbose_name='Rif ', help_text='Ingrese el rif del distribuidor', null=True, max_length=15, blank=True)),
                ('telefono', models.CharField(verbose_name='Número Telefonico ', help_text='Ingrese el telefono del distribuidor', null=True, max_length=12, blank=True)),
                ('email', models.EmailField(verbose_name='Correo electronico ', help_text='Ingrese el correo electronico', null=True, max_length=254, blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 247747), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 247805), auto_now=True)),
                ('banca', models.ForeignKey(verbose_name='Banca (*)', null=True, to='admin_comercializacion.Bancas', blank=True, help_text='Seleccione una banca')),
                ('direccion_id', models.IntegerField(null=True, blank=True)),
                ('status_id', models.IntegerField(verbose_name='Estatus del distribuidor (*)', help_text='Seleccione el status deseado')),
                ('user', models.ForeignKey(null=True, to='admin_users.Users', blank=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(admin_comercializacion.models.BaseGenericProcess, models.Model),
        ),
        migrations.CreateModel(
            name='Operadoras',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(verbose_name='Nombre ', null=True, unique=True, max_length=100, blank=True, help_text='Ingrese nombre de la operadora')),
                ('rif', models.CharField(verbose_name='Rif ', help_text='Ingrese el rif de la operadora', null=True, max_length=15, blank=True)),
                ('telefono', models.CharField(verbose_name='Número Telefonico ', help_text='Ingrese el telefono de la operadora', null=True, max_length=12, blank=True)),
                ('email', models.EmailField(verbose_name='Correo electronico ', null=True, unique=True, max_length=254, blank=True, help_text='Ingrese el correo electronico')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 242196), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 242254), auto_now=True)),
                ('direccion_id', models.IntegerField(null=True, blank=True)),
                ('status_id', models.IntegerField(verbose_name='Estatus de la operadora (*)', help_text='Seleccione el status deseado')),
                ('user', models.ForeignKey(null=True, to='admin_users.Users', blank=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Porcentajes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(null=True, blank=True)),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_maximo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bloque_porc', models.DecimalField(decimal_places=2, default=None, null=True, blank=True, max_digits=15)),
                ('banca_porc', models.DecimalField(decimal_places=2, default=None, null=True, blank=True, max_digits=15)),
                ('distribuidor_porc', models.DecimalField(decimal_places=2, default=None, null=True, blank=True, max_digits=15)),
                ('agencia_porc', models.DecimalField(decimal_places=2, default=None, null=True, blank=True, max_digits=15)),
                ('taquilla_porc', models.DecimalField(decimal_places=2, default=None, null=True, blank=True, max_digits=15)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 258970), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 259036), auto_now=True)),
                ('agencia', models.ForeignKey(null=True, to='admin_comercializacion.Agencias', blank=True)),
                ('banca', models.ForeignKey(null=True, to='admin_comercializacion.Bancas', blank=True)),
                ('bloque', models.ForeignKey(null=True, to='admin_comercializacion.Bloques', blank=True)),
                ('distribuidor', models.ForeignKey(null=True, to='admin_comercializacion.Distribuidores', blank=True)),
                ('operadora', models.ForeignKey(null=True, to='admin_comercializacion.Operadoras', blank=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('valor', models.CharField(max_length=100)),
                ('defecto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 262312), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 262368), auto_now=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PreferenciasCadena',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('valor', models.CharField(blank=True, null=True, max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 263749), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 263805), auto_now=True)),
                ('agencia', models.ForeignKey(null=True, to='admin_comercializacion.Agencias', blank=True)),
                ('banca', models.ForeignKey(null=True, to='admin_comercializacion.Bancas', blank=True)),
                ('bloque', models.ForeignKey(null=True, to='admin_comercializacion.Bloques', blank=True)),
                ('distribuidor', models.ForeignKey(null=True, to='admin_comercializacion.Distribuidores', blank=True)),
                ('preferencia', models.ForeignKey(to='admin_comercializacion.Preferencias')),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TaquillaDataDefault',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_name', models.CharField(max_length=160)),
                ('passwd', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 237870), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 237928), auto_now=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Taquillas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('taquilla', models.CharField(max_length=100)),
                ('serial', models.CharField(blank=True, null=True, max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 252202), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 252262), auto_now=True)),
                ('agencia', models.ForeignKey(verbose_name='Agencia (*)', to='admin_comercializacion.Agencias', help_text='Seleccione una agencia')),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TicketsDataDefault',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pie1', models.CharField(max_length=160)),
                ('pie2', models.CharField(blank=True, null=True, max_length=160)),
                ('pie3', models.CharField(blank=True, null=True, max_length=160)),
                ('titulo1', models.CharField(max_length=160)),
                ('titulo2', models.CharField(blank=True, null=True, max_length=160)),
                ('titulo3', models.CharField(blank=True, null=True, max_length=160)),
                ('everyone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 239097), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 239153), auto_now=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TipoPorcentajes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('bloque', models.BooleanField(default=False)),
                ('banca', models.BooleanField(default=False)),
                ('distribuidor', models.BooleanField(default=False)),
                ('agencia', models.BooleanField(default=False)),
                ('taquilla', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 257246), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 257310), auto_now=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TipoPreferencias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100)),
                ('comparacion', models.IntegerField(choices=[[1, 'Menor'], [2, 'Mayor'], [3, 'Libre']])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 261095), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 261154), auto_now=True)),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UsuariosTaquilla',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=200)),
                ('nombre', models.CharField(blank=True, null=True, max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 253614), auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2014, 12, 16, 21, 55, 48, 253673), auto_now=True)),
                ('taquilla', models.ForeignKey(to='admin_comercializacion.Taquillas')),
            ],
            options={
                'db_tablespace': 'ts_comer',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='tipo',
            field=models.ForeignKey(to='admin_comercializacion.TipoPreferencias'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='preferencias',
            name='user_type',
            field=models.ForeignKey(to='admin_users.UserProfile'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='porcentajes',
            name='taquilla',
            field=models.ForeignKey(null=True, to='admin_comercializacion.Taquillas', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='porcentajes',
            name='tipo',
            field=models.ForeignKey(to='admin_comercializacion.TipoPorcentajes'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='distribuidores',
            unique_together=set([('nombre', 'banca')]),
        ),
        migrations.AddField(
            model_name='cupos',
            name='distribuidor',
            field=models.ForeignKey(null=True, to='admin_comercializacion.Distribuidores', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cupos',
            name='operadora',
            field=models.ForeignKey(null=True, to='admin_comercializacion.Operadoras', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bloques',
            name='operadora',
            field=models.ForeignKey(null=True, to='admin_comercializacion.Operadoras', blank=True),
            preserve_default=True,
        ),
        
        migrations.AddField(
            model_name='bloques',
            name='user',
            field=models.ForeignKey(null=True, to='admin_users.Users', blank=True),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='bloques',
            unique_together=set([('nombre', 'operadora')]),
        ),
        migrations.AddField(
            model_name='bancas',
            name='bloque',
            field=models.ForeignKey(verbose_name='Bloque (*)', null=True, to='admin_comercializacion.Bloques', blank=True, help_text='Seleccione un bloque'),
            preserve_default=True,
        ),
        
        migrations.AddField(
            model_name='bancas',
            name='user',
            field=models.ForeignKey(null=True, to='admin_users.Users', blank=True),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='bancas',
            unique_together=set([('nombre', 'bloque')]),
        ),
        migrations.AddField(
            model_name='agencias',
            name='distribuidores',
            field=models.ForeignKey(verbose_name='Distribuidor (*)', null=True, to='admin_comercializacion.Distribuidores', blank=True, help_text='Seleccione una distribuidor'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='agencias',
            name='user',
            field=models.ForeignKey(null=True, to='admin_users.Users', blank=True),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='agencias',
            unique_together=set([('nombre', 'distribuidores')]),
        ),
    ]
