# Generated by Django 6.0.3 on 2026-03-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAdjunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjunt', models.FileField(upload_to='message_adjunt')),
            ],
            options={
                'verbose_name': 'Adjunto de un mensaje',
                'verbose_name_plural': 'Adjuntos de un mensaje',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Introduzca el asusto del mensaje', max_length=100, verbose_name='Asunto')),
                ('body', models.TextField(blank=True, help_text='Introduzca el texto a enviar', verbose_name='Mensaje')),
                ('priority', models.CharField(choices=[('0', 'Alta'), ('1', 'Media'), ('2', 'Baja')], default='1', help_text='Seleccione la priodidad que desea con la que se envie el mensaje', max_length=1, verbose_name='Prioridad')),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('from_comercializadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora')),
                ('adjunts', models.ManyToManyField(editable=False, related_name='message_adjunts', to='admin_mail.messageadjunt')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='MessageComer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('tray_group', models.CharField(choices=[('1', 'Recibidos'), ('2', 'Enviados'), ('3', 'Archivados'), ('4', 'Papelera')], default='1', max_length=1)),
                ('comercializadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_finanzas.comercializadora')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mail.message')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-message__send_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[('1', 'Simple'), ('2', 'Masivo'), ('3', 'Taquillas')], default='1', max_length=1)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mail.message')),
                ('to_comercializadora', models.ManyToManyField(to='admin_finanzas.comercializadora')),
            ],
            options={
                'verbose_name': 'Mensaje enviados',
                'verbose_name_plural': 'Mensajes enviados',
            },
        ),
    ]
