upstream panel_balanceado{
    server unix:/usr/src/admin_banklotsports/admin_banklotsports_galileo_panel_1.sock;
}
server {
    listen 8090;

    server_name www.matchpointparley.com, matchpointparley.com;
    charset utf-8;

    try_files $uri @panel;

    location /static {
       alias /usr/src/admin_banklotsports/staticfiles;
       expires 365d;
    }

    location /media {
        alias /usr/src/admin_banklotsports/admin_banklotsports/media;
        expires 365d;
    }

    location / {
        proxy_pass http://panel_balanceado;
        proxy_redirect off;
        proxy_read_timeout 5m;
        proxy_set_header Host $host:8090;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}